DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id        BIGINT AUTO_INCREMENT PRIMARY KEY,
  username  VARCHAR(50)  NOT NULL,
  password  VARCHAR(200)  NOT NULL,
  role      VARCHAR(20) NOT NULL
);